"""empty message

Revision ID: 6607082abe8e
Revises: 
Create Date: 2019-05-07 16:20:25.634587

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6607082abe8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('country', sa.Unicode(), nullable=True),
    sa.Column('city', sa.Unicode(), nullable=True),
    sa.Column('login', sa.Unicode(), nullable=True),
    sa.Column('password', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'EUR', 'CAD', 'CNY', name='walletcurrencies'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=True)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_wallet_id', sa.Integer(), nullable=False),
    sa.Column('receiver_wallet_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('sender_wallet_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('receiver_wallet_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('signature', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_datetime'), 'operations', ['datetime'], unique=False)
    op.create_index(op.f('ix_operations_receiver_wallet_id'), 'operations', ['receiver_wallet_id'], unique=False)
    op.create_index(op.f('ix_operations_sender_wallet_id'), 'operations', ['sender_wallet_id'], unique=False)
    op.create_table('operations_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'ACCEPTED', 'FAILED', name='operationstatuses'), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operations_statuses_operation_id'), 'operations_statuses', ['operation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operations_statuses_operation_id'), table_name='operations_statuses')
    op.drop_table('operations_statuses')
    op.drop_index(op.f('ix_operations_sender_wallet_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_receiver_wallet_id'), table_name='operations')
    op.drop_index(op.f('ix_operations_datetime'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
